version: '3.7'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - db:/var/lib/postgresql/data
  bot:
    build: .
    restart: always
    command: python //app//pooling_start.py
    volumes:
      - //app
    depends_on:
      - db
volumes:
  db: {}
  